-- The katamari cannot pick up these entities
return {
  ["arrow"] = 1,
  ["artillery-flare"] = 1,
  ["artillery-projectile"] = 1,
  ["beam"] = 1,
  ["character"] = 1,
  ["character-corpse"] = 1,
  ["corpse"] = 1,
  ["explosion"] = 1,
  ["entity-ghost"] = 1,
  ["flame-thrower-explosion"] = 1,
  ["fire"] = 1,
  ["flying-text"] = 1,
  ["highlight-box"] = 1,
  ["item-request-proxy"] = 1,
  ["leaf-particle"] = 1,
  ["projectile"] = 1,
  ["particle"] = 1,
  ["particle-source"] = 1,
  ["rail-remnants"] = 1,
  ["rocket-silo-rocket"] = 1,
  ["rocket-silo-rocket-shadow"] = 1,
  ["smoke"] = 1,
  ["smoke-with-trigger"] = 1,
  ["speech-bubble"] = 1,
  ["spider-leg"] = 1,
  ["sticker"] = 1,
  ["stream"] = 1,
  ["tile-ghost"] = 1,
}
